name: Car Data Scraper

on:
  # Run daily at 2 AM UTC
  schedule:
    - cron: '0 2 * * *'
  
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      pages:
        description: 'Number of pages to scrape per platform'
        required: false
        default: '2'

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt
          playwright install chromium
          playwright install-deps
      
      - name: Run scrapers
        run: |
          cd backend
          python cli.py --config scraper_config.json --pages ${{ github.event.inputs.pages || '2' }}
      
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add frontend/public/data/listings.json
          git diff --staged --quiet || git commit -m "Update car listings data [$(date +'%Y-%m-%d %H:%M:%S')]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
